### ISSUE TITLE
GetHeapPointer is not safe to use

### ISSUE THREAD

**Issue by fabianoliver** [cklutz/ManagedObjectSize#7]
Hi, great library/attempt at calculating object sizes!

It's a little hard to prove via a specific test as it relies on non-deterministic GC, however I think GetHeapPointer is not safe to use.

It returns a pointer, which is then used to e.g. track if an object has already be visited, and to retrieve array/string component sizes. However, the library does not pin objects (nor could it), so surely GC/heap compaction could happen and invalidate this pointer in between calling GetHeapPointer() and actually doing operations with it.

Maybe GetHeapPointer could be removed entirely,
1.  Track visited objects by reference identity, rather than  by pointer, i.e.: `var considered = new HashSet<ulong>();` would need to be a `HashSet<object>(ReferenceEqualityComparer.Default)`
2. In `GetObjectExclusiveSizeInternal`, calculating `numComponents` could be done via `Unsafe.As<byte,int>(ref GetRawData(obj))` (similar to how the method table is resolved)

**Comment by cklutz** [comment]
Thanks for reporting this.
